version: "3.9"

services:
  minio:
    container_name: minio
    image: quay.io/minio/minio
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - 9000:9000
      - 9001:9001
    command: server /data --console-address ":9001"