app:
  name: file-management
  port: 8080
  allow-file-extensions: pdf|png|jpg
  max-size-file: 5e+6

storage:
  files: ./storage

minio:
  baseUrl: localhost:9000
  id: minioadmin
  secret: minioadmin
  token: 